name: Feature request
description: Suggest an enhancement
labels: ["enhancement"]
body:
  - type: textarea
    id: usecase
    attributes:
      label: Use case
      description: What are you trying to accomplish?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
  - type: textarea
    id: context
    attributes:
      label: Additional context
  - type: checkboxes
    id: checked
    attributes:
      label: Pre-submit checklist
      options:
        - label: I searched existing issues/discussions for duplicates.
          required: true
